FROM ubuntu:latest
RUN apt-get update && apt-get install -y build-essential libssl-dev libffi-dev python3-dev python3-pip
COPY requirements.txt .
RUN pip3 install -r requirements.txt
COPY . .
CMD ["python3", "./app.py"]